### ISSUE TITLE
Doubt with the screenshot feauture

### ISSUE THREAD

**Issue by thezakman** [ivangr0zni/mitm-grabb3r#1]
So I see my b64 POSTs beeing done but there is no file saved in my machine.
Do I need to create a "/capture/scr/" folder and make it writetable?

**Comment by thezakman** [comment]
Sorry I forgot to chmod it, LOL!

**Comment by thezakman** [comment]
is there a delete option, to clear the database or the victims? or only manually in mysql?

**Comment by ivangr0zni** [comment]
Just clear database and /scr/ folder.
